// Users
export const FETCH_ALL_EMPLOYEES = 'FETCH_ALL_EMPLOYEES'
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'